image: maven:latest

variables:
   MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
   MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn compile

test:
  stage: test
  script:
    - mvn test

verify:
  stage: test
  script:
    - mvn verify

deploySnapshot:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS deploy -Dmaven.test.skip=true 
  only: 
   - develop

deployCentral:
  stage: deploy
  before_script:
    ## Add gpg key to sign
    - echo "$GPG_PASSPHRASE"
    - gpg2 --batch --import <(echo "$GPG_PASSPHRASE")
  script:
    - mvn $MAVEN_CLI_OPTS --batch-mode release:prepare -DautoVersionSubmodules=true -Dmaven.test.skip=true
    - mvn release:perform
  only:
    - /^release.*$/

